spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/socialping_db?serverTimezone=Asia/Seoul
    username: root
    password: dbserver

  jwt:
    secretKey: bd706b6c592d3778068f412f180ab015e918d07bcb58e123fa9958f8cc56c26f
    access-token-expire-time: 604800
    refresh-token-expire-time: 2628000

  security.oauth2.client:
    registration:
      facebook:
        client-name: facebook
        client-id: 628641756180672
        client-secret: ecd684c3106d9fdee716f88c48dcae68
        authorization-grant-type: authorization_code
        redirect-uri: http://localhost:8080/login/oauth2/code/facebook
        scope:
          - email
          - public_profile
          - pages_show_list
          - pages_read_engagement
          - business_management
          - instagram_basic