path: http://localhost:8080

spring:
  application:
      name: SocialPing
  config:
    import:
      - application-private.yml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    suffix: .html
    check-template-location: true
    cache: false
    mvc:
      static-path-pattern: /static/**
