spring:
  application:
      name: SocialPing
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/socialping_db?serverTimezone=Asia/Seoul
    username: root
    password: dbserver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
